version: '3.5'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - docker.env
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-sandbox-app
    environment:
      - PORT=${PORT}
    env_file:
      - .env
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-sandbox-pgadmin4
    env_file:
      - docker.env
    ports:
      - '5050:80'
    depends_on:
      - db
